import { Bot, Cpu, Database, GitBranch, ShieldCheck } from "lucide-react";
import { GitHubPermissionGuidance, GuidanceNotice, StartupCheckList, V3_TEXT } from "@patchhivehq/ui-v3";
import { Chip, Fact, money } from "./shared.jsx";

export default function ChecksPanel({ checks, config, health, onRefresh }) {
  const workers = health.worker_capacity || {};
  const aiReady = Boolean(config?.PROVIDER_API_KEY_SET || config?.PATCHHIVE_AI_URL || config?.AI_LOCAL_STATUS?.ok);
  return <div className="mx-auto max-w-[1440px] space-y-6 px-3 py-6 sm:px-6">
    <section className="grid gap-6 lg:grid-cols-[1.5fr_0.7fr]"><article className="surface p-6"><div className={`text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}>Startup evidence</div><div className="flex items-end justify-between gap-4"><h1 className={`mt-2 font-display text-[42px] font-semibold ${V3_TEXT.strong}`}>System checks.</h1><button className="surface-inset h-9 rounded-full px-4 text-[11px]" onClick={onRefresh} type="button">Refresh checks</button></div><div className="mt-7"><StartupCheckList checks={checks}/></div></article><aside className="surface p-6"><div className={`text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}>Unified backend</div><div className={`mt-3 font-display text-[46px] font-semibold ${V3_TEXT.strong}`}>{health.status || "unknown"}</div><div className="mt-6 grid grid-cols-2 gap-3"><Fact label="Database" value={health.db_ok ? "ready" : "error"}/><Fact label="GitHub" value={health.github_ready ? "verified" : "unverified"}/><Fact label="Agents" value={health.agents || 0}/><Fact label="Lifetime cost" value={money(health.lifetime_cost)}/></div></aside></section>
    <section className="grid gap-6 lg:grid-cols-2"><article className="surface p-6"><div className={`flex items-center gap-2 text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}><GitBranch size={12}/> GitHub write path</div><div className="mt-5 grid grid-cols-2 gap-3"><Fact label="Write token" value={health.github?.token_verified ? "verified" : health.github?.token_configured ? "unverified" : "missing"}/><Fact label="Identity" value={health.bot || "not set"}/><Fact label="PR action" value="guarded"/><Fact label="Watch mode" value={health.watch_mode ? "enabled" : "disabled"}/></div><GitHubPermissionGuidance>A classic PAT with the repository write scope powers fork, branch, issue-comment, and PR delivery. Startup verifies identity; only a successful target operation proves target write permission.</GitHubPermissionGuidance></article><article className="surface p-6"><div className={`flex items-center gap-2 text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}><Cpu size={12}/> Execution state</div><div className="mt-5 grid grid-cols-2 gap-3"><Fact label="Engine" value={health.run_active ? "active" : "idle"}/><Fact label="Worker limit" value={workers.limit || 0}/><Fact label="Workers active" value={workers.active || 0}/><Fact label="Workers available" value={workers.available || 0}/></div><div className="mt-4 flex flex-wrap gap-2"><Chip tone={aiReady ? "ok" : "hot"}>AI {aiReady ? "configured" : "missing"}</Chip><Chip tone={config?.REPO_REAPER_GITHUB_TOKEN_RW_SET ? "ok" : "hot"}>GitHub write token</Chip><Chip tone={config?.WEBHOOK_SECRET_SET ? "ok" : "neutral"}>webhook {config?.WEBHOOK_SECRET_SET ? "signed" : "manual only"}</Chip></div></article></section>
    <section className="surface p-6"><div className={`flex items-center gap-2 text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}><Database size={12}/> Product state</div><div className="surface-inset mt-5 rounded-xl p-3"><div className={`text-[10px] uppercase tracking-wider ${V3_TEXT.mute}`}>Database path</div><div className={`mt-1 break-all text-[12px] ${V3_TEXT.strong}`}>{health.db_path || "unknown"}</div></div><div className="mt-4 flex flex-wrap gap-2"><Chip tone={health.db_ok ? "ok" : "hot"}>database {health.db_ok ? "ready" : "unavailable"}</Chip><Chip tone={health.auth_enabled ? "ok" : "warn"}>browser auth {health.auth_enabled ? "enabled" : "disabled"}</Chip><Chip tone={health.config_errors ? "hot" : "ok"}>{health.config_errors || 0} startup errors</Chip></div></section>
    <section className="surface p-6"><div className={`flex items-center gap-2 text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}><ShieldCheck size={12}/> Write and test boundary</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><GuidanceNotice label="Validation proof">Only a typed passed test result permits a non-draft autonomous PR. Disabled or unavailable tests are not treated as success.</GuidanceNotice><GuidanceNotice label="Sandbox policy">Untrusted repositories cannot run host tests unless the explicit trusted/sandbox policy allows it.</GuidanceNotice><GuidanceNotice label="Cross-product context">RepoMemory constraints, FailGuard guardrails, TrustGate policy, existing PRs, and HiveCore suite budgets remain independent gates.</GuidanceNotice></div></section>
  </div>;
}
