import { ExternalLink, GitPullRequest, RefreshCw } from "lucide-react";
import { GuidanceNotice, ProgressiveList, V3_TEXT } from "@patchhivehq/ui-v3";
import { Chip, formatDate, statusTone } from "./shared.jsx";

export default function PrPanel({ busy, onRefresh, onRefreshPr, prs }) {
  const open = prs.filter((item) => item.state === "open" && !item.merged).length;
  const merged = prs.filter((item) => item.merged).length;
  return <div className="mx-auto max-w-[1440px] space-y-6 px-3 py-6 sm:px-6">
    <section className="surface p-6 sm:p-8"><div className={`flex items-center gap-2 text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}><GitPullRequest size={12}/> Delivery watch</div><h1 className={`mt-2 font-display text-[42px] font-semibold ${V3_TEXT.strong}`}>Pull request monitor.</h1><p className={`mt-3 max-w-3xl text-[13px] leading-relaxed ${V3_TEXT.body}`}>Tracks the PRs RepoReaper actually opened, their latest GitHub state, merge outcome, and source run. This is lifecycle evidence—not a merge recommendation.</p><div className="mt-5 flex flex-wrap gap-2"><Chip tone="ok">{open} open</Chip><Chip tone="ok">{merged} merged</Chip><Chip>{prs.length} tracked</Chip><button className={`surface-inset inline-flex h-9 items-center gap-2 rounded-full px-4 text-[11px] ${V3_TEXT.body}`} disabled={busy} onClick={onRefresh} type="button"><RefreshCw size={12}/>{busy ? "Refreshing…" : "Refresh list"}</button></div></section>
    <section className="surface p-6"><div className={`text-[10px] uppercase tracking-[0.22em] ${V3_TEXT.mute}`}>Tracked deliveries</div><div className="mt-5"><ProgressiveList initialCount={6} batchCount={25} itemLabel="pull requests" items={prs} empty={<div className={`surface-inset rounded-xl p-10 text-center text-[12px] ${V3_TEXT.mute}`}>No RepoReaper pull requests are tracked yet.</div>} renderItem={(pr) => <article className="surface-inset rounded-xl p-4" key={`${pr.repo}-${pr.pr_number}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className={`font-display text-[18px] font-semibold ${V3_TEXT.strong}`}>{pr.repo} · PR #{pr.pr_number}</h2><p className={`mt-1 text-[11px] ${V3_TEXT.mute}`}>Run {pr.run_id} · opened {formatDate(pr.opened_at)} · checked {formatDate(pr.last_checked)}</p></div><div className="flex flex-wrap gap-2"><Chip tone={pr.merged ? "ok" : statusTone(pr.state)}>{pr.merged ? "merged" : pr.state}</Chip><Chip>{pr.review_state || "review unknown"}</Chip></div></div><div className="mt-3 flex flex-wrap gap-2"><a className="surface-inset inline-flex h-9 items-center gap-2 rounded-full px-3 text-[11px]" href={`https://github.com/${pr.repo}/pull/${pr.pr_number}`} rel="noreferrer" target="_blank">Open PR <ExternalLink size={11}/></a><button className={`surface-inset inline-flex h-9 items-center gap-2 rounded-full px-3 text-[11px] ${V3_TEXT.body}`} disabled={busy} onClick={() => onRefreshPr(pr)} type="button"><RefreshCw size={11}/>Refresh GitHub state</button></div></article>}/></div></section>
    <GuidanceNotice label="Lifecycle boundary">RepoReaper polls delivery state and may clean up its source branch after merge. MergeKeeper, ReviewBee, TrustGate, FlakeSting, and ReleaseSentry remain the products that interpret merge, review, policy, CI, and release readiness.</GuidanceNotice>
  </div>;
}
