export const METRICS = [
  { label: "Repos scanned", value: "8", tone: "sig", sub: "complete" },
  { label: "Signals found", value: "142", tone: "warn", sub: "+18 vs prior" },
  { label: "Stale issues", value: "67", tone: "hot", sub: "45+ days" },
  { label: "Duplicate pairs", value: "23", tone: "", sub: "likely matches" },
  { label: "Recurring bugs", value: "11", tone: "ok", sub: "cluster leads" },
];

export const RADAR_WINDOWS = {
  7: { label: "7 day live pass", count: "5 signals", outer: "7d", mid: "3d", inner: "24h" },
  14: { label: "14 day history pass", count: "8 signals", outer: "14d", mid: "7d", inner: "3d" },
  30: { label: "30 day deep sweep", count: "11 signals", outer: "30d", mid: "14d", inner: "7d" },
};

export const RADAR_REPOS = [
  {
    repo: "tokio-rs/tokio",
    label: "tokio 87",
    tone: "red",
    minWindow: 7,
    position: { left: "69%", top: "31%" },
    pingDelay: "0s",
    score: "87",
    stale: "22/30",
    dupes: "7",
    markers: "53",
    trend: "+14",
    vector: "047",
    gain: "82%",
    summary: "High stale backlog pressure with recurring timeout-related bug clusters and cancellation duplicates.",
  },
  {
    repo: "serde-rs/serde",
    label: "serde 61",
    tone: "amber",
    minWindow: 7,
    position: { left: "43%", top: "57%" },
    pingDelay: ".4s",
    score: "61",
    stale: "14/30",
    dupes: "3",
    markers: "21",
    trend: "+3",
    vector: "164",
    gain: "64%",
    summary: "Moderate stale backlog with unlabeled derive macro edge cases forming a recurring cluster.",
  },
  {
    repo: "vercel/next.js",
    label: "next.js 38",
    tone: "blue",
    minWindow: 7,
    position: { left: "24%", top: "37%" },
    pingDelay: ".8s",
    score: "38",
    stale: "8/30",
    dupes: "4",
    markers: "n/a",
    trend: "-11",
    vector: "286",
    gain: "41%",
    summary: "Stale issue count is improving, but App Router middleware reports still repeat across the sample.",
  },
  {
    repo: "django/django",
    label: "django 58",
    tone: "amber",
    minWindow: 7,
    position: { left: "58%", top: "72%" },
    pingDelay: "1.1s",
    score: "58",
    stale: "18/30",
    dupes: "4",
    markers: "31",
    trend: "+8",
    vector: "205",
    gain: "59%",
    summary: "Older regression reports are gathering around auth and migration workflows.",
  },
  {
    repo: "fastapi/fastapi",
    label: "fastapi 41",
    tone: "green",
    minWindow: 7,
    position: { left: "69%", top: "63%" },
    pingDelay: "1.5s",
    score: "41",
    stale: "10/30",
    dupes: "2",
    markers: "18",
    trend: "-2",
    vector: "096",
    gain: "47%",
    summary: "Backlog pressure is stable; stale reports are present but not clustering hard.",
  },
  {
    repo: "rails/rails",
    label: "rails 72",
    tone: "red",
    minWindow: 14,
    position: { left: "64%", top: "18%" },
    pingDelay: ".2s",
    score: "72",
    stale: "21/30",
    dupes: "6",
    markers: "44",
    trend: "+10",
    vector: "019",
    gain: "76%",
    summary: "Two-week view surfaces persistent ActiveRecord regression reports and duplicate stale bugs.",
  },
  {
    repo: "nodejs/node",
    label: "node 57",
    tone: "amber",
    minWindow: 14,
    position: { left: "30%", top: "72%" },
    pingDelay: ".9s",
    score: "57",
    stale: "15/30",
    dupes: "5",
    markers: "28",
    trend: "+5",
    vector: "242",
    gain: "63%",
    summary: "Issue pressure is rising around module resolution and platform-specific failures.",
  },
  {
    repo: "rust-lang/rust",
    label: "rust 44",
    tone: "blue",
    minWindow: 14,
    position: { left: "38%", top: "22%" },
    pingDelay: "1.3s",
    score: "44",
    stale: "11/30",
    dupes: "2",
    markers: "35",
    trend: "+1",
    vector: "333",
    gain: "52%",
    summary: "Signals are broad but lower urgency; compiler diagnostics reports appear repeatedly.",
  },
  {
    repo: "kubernetes/kubernetes",
    label: "k8s 66",
    tone: "red",
    minWindow: 30,
    position: { left: "73%", top: "45%" },
    pingDelay: ".5s",
    score: "66",
    stale: "19/30",
    dupes: "7",
    markers: "62",
    trend: "+6",
    vector: "071",
    gain: "72%",
    summary: "Thirty-day sweep reveals recurring scheduler and networking issue families.",
  },
  {
    repo: "facebook/react",
    label: "react 52",
    tone: "amber",
    minWindow: 30,
    position: { left: "36%", top: "15%" },
    pingDelay: "1.7s",
    score: "52",
    stale: "13/30",
    dupes: "4",
    markers: "24",
    trend: "+2",
    vector: "318",
    gain: "55%",
    summary: "Older hook-related reports remain visible but not sharply escalating.",
  },
  {
    repo: "pytest-dev/pytest",
    label: "pytest 35",
    tone: "green",
    minWindow: 30,
    position: { left: "66%", top: "78%" },
    pingDelay: "2s",
    score: "35",
    stale: "7/30",
    dupes: "1",
    markers: "16",
    trend: "-4",
    vector: "122",
    gain: "39%",
    summary: "Longer range adds low-priority fixture cleanup signals without strong recurrence.",
  },
];

export const RADAR_ECHOES = [
  { tone: "amber", minWindow: 14, position: { left: "48%", top: "68%" } },
  { tone: "blue", minWindow: 14, position: { left: "20%", top: "52%" } },
  { tone: "red", minWindow: 30, position: { left: "55%", top: "24%" } },
  { tone: "blue", minWindow: 30, position: { left: "68%", top: "52%" } },
  { tone: "amber", minWindow: 30, position: { left: "18%", top: "64%" } },
  { tone: "blue", minWindow: 30, position: { left: "58%", top: "86%" } },
];

export const QUEUE = [
  {
    repo: "tokio-rs/tokio",
    score: "87",
    scoreTone: "hot",
    tags: ["Rust", "escalating", "847 issues"],
    drivers: [
      { name: "stale ratio", width: "90%", tone: "red", value: "+28" },
      { name: "recurring bugs", width: "66%", tone: "amber", value: "+20" },
      { name: "duplicates", width: "58%", tone: "amber", value: "+17" },
    ],
  },
  {
    repo: "serde-rs/serde",
    score: "61",
    scoreTone: "warn",
    tags: ["Rust", "nominal", "312 issues"],
    description: "Unlabeled edge-case reports are clustering around derive macro failures.",
  },
  {
    repo: "vercel/next.js",
    score: "38",
    scoreTone: "ok",
    tags: ["TypeScript", "recovering", "2.1k issues"],
    description: "Stale issue count is improving. Middleware cluster still repeats across reports.",
  },
];

export const EVIDENCE = [
  { title: "73 percent of sampled Tokio issues are stale.", meta: "30 issue sample - 45 day threshold", tone: "red", label: "high" },
  { title: "Timeout reports share cancellation terms.", meta: "12 reports - 5 duplicate candidates", tone: "amber", label: "cluster" },
  { title: "TODO/FIXME density is rising in async paths.", meta: "41 TODO - 12 FIXME", tone: "signal", label: "marker" },
];
