// Latency and uptime, from HiveCore's own health probes.
//
// Both numbers used to be fiction. `latencyMs` on every product card came from a
// constant in hive-data.ts, and the sparkline beside it was 60 samples generated by a
// seeded PRNG using that constant as a base. Uptime was a second constant. Nothing in
// the stack measured either one.
//
// HiveCore now times each /health request and retains a bounded ring of samples per
// product. Latency history and uptime are computed from the same rows, so the graph
// and the percentage beside it cannot disagree.

import { useEffect, useState } from "react";
import { apiFetch } from "./http";

export interface ProbeSample {
  observed_at: string;
  latency_ms: number;
  healthy: boolean;
}

export interface ProbeStats {
  samples: number[];
  /** Share of retained probes that succeeded, or null when nothing is retained. */
  uptime: number | null;
  p50: number | null;
  p95: number | null;
  /** How many observations these are drawn from — the denominator, stated. */
  observations: number;
  latest: number | null;
}

export type ProbeEvidenceState = "observed" | "failed" | "not_observed" | "not_applicable";

interface ProbeEvidence {
  state: ProbeEvidenceState;
  reason: string;
}

const BASE = "/api/products/hive-core";

interface Envelope<T> {
  data?: T;
}

export async function fetchProbes(slug: string, signal?: AbortSignal): Promise<ProbeSample[]> {
  const response = await apiFetch(`${BASE}/products/${slug}/probes`, { signal });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const body = (await response.json()) as Envelope<ProbeSample[]>;
  if (!Array.isArray(body.data)) {
    throw new Error("Probe response did not contain an observed sample collection.");
  }
  return body.data;
}

function percentile(sorted: number[], p: number): number | null {
  if (sorted.length === 0) return null;
  const index = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length));
  return sorted[index];
}

/**
 * Summarise retained probes.
 *
 * Every field is null when there is nothing to compute it from. A zero would be a
 * claim — 0ms latency, 0% uptime — and the caller must be able to tell "no data" from
 * "bad data", which is the distinction the old generator erased by always answering.
 */
export function summarise(probes: ProbeSample[]): ProbeStats {
  // Latency percentiles use successful probes only. A failed probe has no meaningful
  // round-trip time, and mixing timeouts into the distribution would report a product
  // as slow when it was actually down — two states that need different responses.
  const successful = probes.filter((probe) => probe.healthy).map((probe) => probe.latency_ms);
  const sorted = [...successful].sort((a, b) => a - b);

  return {
    samples: successful,
    // Uptime, by contrast, is over *all* retained probes: excluding failures would
    // make it unconditionally 100%.
    uptime: probes.length === 0 ? null : probes.filter((probe) => probe.healthy).length / probes.length,
    p50: percentile(sorted, 50),
    p95: percentile(sorted, 95),
    observations: probes.length,
    latest: successful.length === 0 ? null : successful[successful.length - 1],
  };
}

/** Retained probes for one product, refreshed when the live sync ticks. */
export function useProbes(
  slug: string | null,
  syncVersion = 0,
): ProbeStats & ProbeEvidence & { loading: boolean } {
  const [probes, setProbes] = useState<ProbeSample[]>([]);
  const [evidence, setEvidence] = useState<ProbeEvidence>({
    state: "not_observed",
    reason: "Probe history has not been requested yet.",
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!slug) {
      setProbes([]);
      setEvidence({ state: "not_observed", reason: "No product was selected." });
      setLoading(false);
      return;
    }
    if (slug === "hive-core") {
      setProbes([]);
      setEvidence({
        state: "not_applicable",
        reason: "HiveCore reads itself in-process; there is no network probe.",
      });
      setLoading(false);
      return;
    }
    const controller = new AbortController();
    setLoading(true);
    fetchProbes(slug, controller.signal)
      .then((samples) => {
        setProbes(samples);
        setEvidence({
          state: "observed",
          reason: samples.length === 0 ? "Probe history was observed and is empty." : "",
        });
      })
      .catch((cause) => {
        if (cause instanceof DOMException && cause.name === "AbortError") return;
        setProbes([]);
        setEvidence({
          state: "failed",
          reason: cause instanceof Error ? cause.message : "Probe history could not be read.",
        });
      })
      .finally(() => setLoading(false));
    return () => controller.abort();
  }, [slug, syncVersion]);

  return { ...summarise(probes), ...evidence, loading };
}
